modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/SmellyModder/Seeker-Compass/issues"
license = "https://github.com/SmellyModder/Seeker-Compass/blob/1.16.5/LICENSE"

[[mods]]
    modId="seeker_compass"
    namespace="seeker_compass"
    version="3.0.0"
    displayName="Seeker Compass"
    authors="SmellyModder (Luke Tonon), Five/Paradiscal"
    description='''Adds a new magical compass that has unique enchantments and is capable of tracking living entities.'''
    displayURL=""

[[dependencies.seeker_compass]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"

[[dependencies.seeker_compass]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.2.0,)"
    ordering = "AFTER"
    side = "BOTH"
